id: P009576
initial_creation_type: ocr
source_metadata:
  id: bdr:W20133
  title: སྟོན་གྱི་རང་སྒྲ།
  author: ''
  volumes:
    5d291dcd08924b0d9f80e166a52efa90:
      image_group_id: I1KG24188
      title: ''
      volume_number: 1
      total_pages: 444
