id: P009576
initial_creation_type: ocr
created_at: 29/03/2020
last_modified_at: 2021-12-19 20:38:55.518297
source_metadata:
  id: bdr:W20133
  title: སྟོན་གྱི་རང་སྒྲ།
  author: ''
  volumes:
    5d291dcd08924b0d9f80e166a52efa90:
      image_group_id: I1KG24188
      title: ''
      volume_number: 1
      total_pages: 444
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: true
